name: medi
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.2
  intl: ^0.18.1
  flutter_local_notifications: ^15.1.0+1
  timezone: ^0.9.2
  flutter_native_timezone_updated_gradle: ^2.0.3
  permission_handler: ^10.4.3
  path_provider: ^2.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  fonts:
    - family: GmarketSansTTF
      fonts:
        - asset: assets/font/gmarket/GmarketSansTTFLight.ttf
          weight: 300
        - asset: assets/font/gmarket/GmarketSansTTFMedium.ttf
          weight: 500
        - asset: assets/font/gmarket/GmarketSansTTFBold.ttf
          weight: 700
